### PR TITLE
fixing replace -rewriteall by -crosssection

### PR DESCRIPTION
**Pull request by ahmad88me**

### CODE REVIEW

**Comment by mariapoveda** [comment]
Does this rewrite only crossref and overview sections?

**Comment by ahmad88me** [comment]
@mariapoveda yes it supposed to be, but I reverted back because Widoco was not generating the documentation with the new flag.

**Comment by dgarijo** [comment]
I have tried and it works, both through console and gui. I cannot reproduce the error you describe.

**Comment by ahmad88me** [comment]
@dgarijo I'm gonna check the flag that is causing the issue, if found I'll send you a vagrant file ;)

**Pull request merged**
